### ISSUE TITLE
Update glitch

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/powered-pixel-dungeon#66] opened 2020-10-30 20:14 UTC
some ver. ago i start notice, what after update all old mobs become completelly insane, attacking everyone, including bosses, undetected mimics and shopkeepers. Also they start falling into the void and stepping on trapped tiles(and piranhas start dropping themselves out of water, but somewhy very rare). But new-spawned mobs don't do anything innormal

**Comment by Smujb** [comment] 2020-10-30 20:29
Uhhhh..... This makes absolutely no sense... Will look into it, but since it's after an update, it has slim chance of being fixed unless it can be reproduced on a fresh save

**Comment by Smujb** [comment] 2020-11-14 10:52
Ah, I think I get it. I made alignment bundleable, so mobs tried to restore alignment and got null.

Essentially, they had no alignment and acted crazy. Gonna close this as there's not an easy fix and it 100% will only affect old saves from that specific version. Next update writes off save compatibility anyway.

**Closed by Smujb** 2020-11-14 10:52 UTC
